domain_path: S:\Codes\mandelbrot_super_accelerator\vitis\platform1\export\platform1\sw\bsp_lwip2
app_src_dir: S:\programs\vivado\2025.1\Vitis\data\embeddedsw\lib\sw_apps\lwip_echo_server
template: lwip_echo_server
lang: c
